{% set name = "fortranformat" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 30e9e511f8f61ddf7bbde7571fadd512714bd5ab2f0ba85748c8513791cbf8ef

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
  run:
    - python

test:
  imports:
    - fortranformat

about:
  home: http://bitbucket.org/brendanarnold/py-fortranformat
  license: MIT
  license_family: MIT
  license_file: COPYING.txt
  summary: Mimics Fortran textual IO in Python
  description: "FORTRAN format interpreter for Python\nGenerates text from a Python list of variables or will read a line of text into Python variables according  to the FORTRAN format statement passed.\n\nThe library is extensively unit-tested  against the Intel FORTRAN compiler on a Linux platform. Differences between\
    \ platforms/compilers are generally minor."
  doc_url: https://bitbucket.org/brendanarnold/py-fortranformat/wiki/Home
  dev_url: http://bitbucket.org/brendanarnold/py-fortranformat

extra:
  recipe-maintainers:
    - smithsp
