{% set name = "fortranformat" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1e765c01a66208d54d75cae140ba9f1adda0548aaad8538cba8da39e69ac178c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core
  run:
    - python >={{ python_min }}

test:
  imports:
    - fortranformat
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/brendanarnold/py-fortranformat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Mimics Fortran textual IO in Python
  description: "FORTRAN format interpreter for Python.\nGenerates text from a Python list of variables or will read a line of text into Python variables according to the FORTRAN format statement passed."
  doc_url: https://github.com/brendanarnold/py-fortranformat/blob/master/docs/wiki/guide.md
  dev_url: https://github.com/brendanarnold/py-fortranformat

extra:
  recipe-maintainers:
    - smithsp
    - alexmalins
